export * from './NotFound/not-found'
export * from './Landing/landing'
export * from './Home/home'
export * from './VideogameDetailCard/videogame-detail-card'
export * from './VideogameForm/videogame-form'
export * from './AboutMe/about-me'
